version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: lms-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Qwerty@1
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: mounika2608/lms-backend:latest
    build:
      context: ./api/
      dockerfile: Dockerfile
    environment:
      - MODE=local
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:Qwerty@1@db:5432/mydb
    ports:
      - "8081:8081"
    depends_on: # Removed 'condition: service_healthy'
      db :
         condition: service_healthy
      
  frontend:
    image: mounika2608/lms-frontend:latest
    build:
      context: ./webapp/
      dockerfile: Dockerfile
    environment:
      - MODE=local
      - API_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on: # Removed 'condition: service_started' implicitly by removing the backend 'depends_on' condition as well.
      - backend

volumes:
  postgres_data: